name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          COMMIT_HASH=${git rev-parse --short HEAD}
          docker build -t kee08/test:${COMMIT_HASH} .
          

      - name: Push Docker Image
        run: |
          COMMIT_HASH=${git rev-parse --short HEAD}
          docker push kee08/test:${COMMIT_HASH}
