
name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.repository }}:${{ github.sha }}
          LATEST_TAG=${{ github.repository }}:latest
          docker build -t $IMAGE_TAG $LATEST_TAG .
          
      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ github.repository }}:${{ github.sha }}
          LATEST_TAG=${{ github.repository }}:latest
          docker push $IMAGE_TAG
          docker push $LATEST_TAG
