name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG$="{{ github.sha }}"
          docker build -t ${{ github.repository }}:$IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          echo "Pushing Docker image"
          docker push ${{ env.IMAGE_TAG }}
