name: Docker CI
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull previous latest image
      run: |
        docker pull ${{ github.repository }}:latest || true

    - name: Tag previous latest image with previous SHA
      run: |
        PREVIOUS_TAG=${{ github.repository }}:previous
        docker tag ${{ github.repository }}:latest $PREVIOUS_TAG || true

    - name: Build Docker Image
      run: |
        IMAGE_TAG=${{ github.repository }}:${{ github.sha }}
        LATEST_TAG=${{ github.sha }}:latest
        docker build -t ${{ IMAGE_TAG }} .
        docker tag ${{ IMAGE_TAG }} $LATEST_TAG

    - name: Push Docker Image
      run: |
        IMAGE_TAG=${{ github.repository }}:${{ github.sha }}
        LATEST_TAG=${{ github.sha }}:latest
        PREVIOUS_TAG=${{ github.repository }}:previous
        docker push $IMAGE_TAG
        docker push $LATEST_TAG
        docker push $PREVIOUS_TAG
