name: Build and Push Docker Images
on:
 push:
  branch: 
   - main

jobs:
 build: 
  runs-on: ubuntu-latest
  steps:

   - name: checkout code
     uses: action/checkout@v3
     
   - name: setup docker buildx 
     uses: docker-setup-buildx-action@v2

   - name: login to docker hub
     uses: docker/login-action@v2
     with:
      username: ${{ secret.DOCKER_HUB_USERNAME }}
      password: ${{ secret.DOCKER_HUB_ACCESS_TOKEN }}

   - name: build docker image
     uses: docker build -t my-docker-image:latest .

   - name: push docker image
     uses: docker push my-docker-image:latest
