name: Docker CI
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Get short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        IMAGE_TAG=${{ github.repository }}:${{ env.SHORT_SHA }}
        LATEST_TAG=${{ github.repository }}:latest
        docker build -t $IMAGE_TAG .
        docker tag $IMAGE_TAG $LATEST_TAG

    - name: Push Docker Image
      run: |
        IMAGE_TAG=${{ github.repository }}:${{ env.SHORT_SHA }}
        LATEST_TAG=${{ github.repository }}:latest
        docker push $IMAGE_TAG
        docker push $LATEST_TAG
