name: Build and Push Docker Image
on:
 push:
  branch: - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
     - name: checkout code
       uses: action/checkout@v3

     - name: setup docker buildx
       uses: docker-setup-buildx-action@v2

     - name: build docker image
       run: |
         docker build -t my-docker-image:latest .

     - name: login to docker hun
       uses: docker/login-action@v2
       with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

     - name: push docker image
       run: |
         docker push my-docker-image:latest
